- .github/workflows/build.yml
- Velopack.sln
- examples/AvaloniaCrossPlat/dev-scripts/build-win.bat
- src/Velopack.Deployment/_Repository.cs
- src/Velopack.Packaging.Unix/Velopack.Packaging.Unix.csproj
- src/Velopack.Packaging.Windows/Commands/WindowsPackCommandRunner.cs
- src/Velopack.Packaging.Windows/HostModel/Bundle/Bundler.cs
- src/Velopack.Packaging.Windows/Velopack.Packaging.Windows.csproj
- src/Velopack.Packaging/BuildAssets.cs
- src/Velopack.Packaging/DeltaPackageBuilder.cs
- src/Velopack.Packaging/PackageBuilder.cs
- src/Velopack.Packaging/ReleaseEntryHelper.cs
- src/Velopack.Packaging/Velopack.Packaging.csproj
- src/Velopack.Vpk/Commands/_BaseCommand.cs
- src/Velopack.Vpk/Logging/BasicConsole.cs
- src/Velopack/Locators/WindowsVelopackLocator.cs
- src/Velopack/ReleaseEntry.cs
- src/Velopack/Sources/SimpleWebSource.cs
- src/Velopack/UpdateExe.cs
- src/Velopack/UpdateManager.cs
- src/Velopack/VelopackAsset.cs
Minor code cleanup and spelling fixes
> Adding netstandard 2.0 support for packaging projects

- examples/AvaloniaCrossPlat/AvaloniaCrossPlat.csproj
- src/Velopack.Vpk/Velopack.Vpk.csproj
- src/Velopack/Velopack.csproj
- test/Directory.Build.props
- test/Velopack.Packaging.Tests/Velopack.Packaging.Tests.csproj
The key update here is NuGet.Packaging to address CVE-2024-0057
https://github.com/advisories/GHSA-68w7-72jg-6qpp
> Updating several NuGet packages

- src/Velopack.Build/HmacAuthHttpClientHandler.cs
- src/Velopack.Build/PublishTask.cs
- src/Velopack.Build/Velopack.Build.targets
- src/Velopack.Packaging/Flow/HmacHelper.cs
- src/Velopack.Packaging/Flow/UploadOptions.cs
- src/Velopack.Packaging/Flow/VelopackFlowServiceClient.cs
- src/Velopack.Packaging/Flow/VelopackServiceOptions.cs
- src/Velopack.Vpk/Commands/Flow/VelopackServiceCommand.cs
This leverage the API HMAC auth of Velopack FLOW
> Adding in API key support

- src/Velopack.Packaging/ReleaseEntryHelper.cs
> Do not include deltas when writing Squirrel RELEASES file

- src/Velopack.Deployment/_ObjectRepository.cs
> ObjectRepository: don't include deltas in Squirrel RELEASES file

- src/Velopack.Build/packages.lock.json
- src/Velopack.Deployment/packages.lock.json
- src/Velopack.Packaging.Unix/packages.lock.json
- src/Velopack.Packaging.Windows/packages.lock.json
- src/Velopack.Packaging/Velopack.Packaging.csproj
- src/Velopack.Packaging/packages.lock.json
- src/Velopack.Vpk/packages.lock.json
Fixes: https://github.com/advisories/GHSA-m5vv-6r4h-3vj9
> Updating Microsoft.Identity.Client to fix vunerability

- src/Velopack.Deployment/S3Repository.cs
- src/Velopack.Vpk/Commands/Deployment/S3BaseCommand.cs
Fixes https://github.com/velopack/velopack/issues/168
Fixes #148
> add s3 prefix support

- src/Velopack/packages.lock.json
- test/Divergic.Logging.Xunit/Divergic.Logging.Xunit.csproj
- test/Velopack.Tests/Velopack.Tests.csproj
https://github.com/advisories/GHSA-hh2w-p6rv-4g7w
> Update to address CVE-2024-30105

- src/vpk/Velopack.Deployment/Velopack.Deployment.csproj
https://www.nuget.org/packages/Gitea.Net.API/1.0.0
> Fix CVE-2024-30105

- src/vpk/Velopack.Vpk/Velopack.Vpk.csproj
- test/Velopack.Packaging.Tests/Velopack.Packaging.Tests.csproj
Addresses https://github.com/advisories/GHSA-447r-wph3-92pm
> Fix CVE-2024-38095

- src/vpk/Velopack.Build/Velopack.Build.csproj
https://github.com/advisories/GHSA-hq7w-xv5x-g34j
> Fix CVE-2024-38081

- src/vpk/Velopack.Build/PublishTask.cs
- src/vpk/Velopack.Packaging/Flow/VelopackFlowServiceClient.cs
- src/vpk/Velopack.Packaging/HttpClientExtensions.cs
- src/vpk/Velopack.Vpk/Commands/Flow/ApiCommand.cs
- src/vpk/Velopack.Vpk/Commands/Flow/ApiCommandRunner.cs
- src/vpk/Velopack.Vpk/Commands/Flow/ApiOptions.cs
- src/vpk/Velopack.Vpk/Commands/Flow/LoginCommandRunner.cs
- src/vpk/Velopack.Vpk/Commands/_BaseCommand.cs
- src/vpk/Velopack.Vpk/Logging/SpectreConsoleSink.cs
- src/vpk/Velopack.Vpk/OptionMapper.cs
- src/vpk/Velopack.Vpk/Program.cs
This provide a hidden Velopack Flow API command. This allows for easier scripting directly against the API as it leveraging the built in auth.
> Adding flow API command

- src/lib-csharp/UpdateExe.cs
- src/lib-csharp/UpdateManager.Helpers.cs
- src/lib-csharp/UpdateManager.cs
> Add async overload for WaitExitThenApplyUpdates (see #213)

- src/vpk/Velopack.Packaging.Unix/AppImageTool.cs
> Use zstd compression for appimage (#221)

- src/vpk/Velopack.Packaging/Flow/CreateReleaseGroupRequest.cs
- src/vpk/Velopack.Packaging/Flow/UpdateReleaseGroupRequest.cs
- src/vpk/Velopack.Packaging/Flow/VelopackFlowServiceClient.cs
- src/vpk/Velopack.Packaging/HttpClientExtensions.cs
- test/Velopack.Packaging.Tests/WindowsPackTests.cs
After uploading release assets mark the release group as published.
> Publish release group after uploading assets.

- src/vpk/Velopack.Build/Velopack.Build.csproj
https://github.com/advisories/GHSA-hq7w-xv5x-g34j
> Updating dependency

- src/lib-nodejs/velopack_nodeffi/build.rs
- src/vpk/Velopack.Build/Velopack.Build.csproj
- src/vpk/Velopack.Packaging.Windows/SetupBundle.cs
- src/vpk/Velopack.Packaging/DeltaPackageBuilder.cs
- src/vpk/Velopack.Vpk/Commands/_BaseCommand.cs
I bundled these four changes to cut down on the spam, however, all four commits can stand on their own.
> Warnings and fixes

- src/bins/src/windows/shortcuts.rs
> Create start-menu author shortcut directory if not exists

- src/vpk/Velopack.Packaging.Unix/Commands/LinuxPackCommandRunner.cs
> Add X-AppImage-Version to .desktop file

- src/bins/src/setup.rs
> Don't open a dialog when running setup.exe --help

- src/lib-cpp/include/Velopack.h
- src/lib-cpp/include/Velopack.hpp
- src/lib-cpp/src/lib.rs
- src/lib-cpp/src/types.rs
> Fix memory violation crash for lib-cpp when there is no download progress callback

- src/vpk/Velopack.Packaging.Unix/Commands/LinuxPackCommandRunner.cs
- test/Velopack.Packaging.Tests/CrossCompile.cs
> Add .DirIcon to AppImages and lint AppImage on cross compile

- Cargo.lock
- src/bins/Cargo.toml
- src/bins/src/commands/apply.rs
- src/bins/src/commands/apply_windows_impl.rs
- src/bins/src/lib.rs
- src/bins/src/shared/util_common.rs
- src/bins/src/windows/mod.rs
> Vastly simplify windows update for now

- src/vpk/Velopack.Deployment/GitHubRepository.cs
> possibly fix the github timeout issue

- samples/CSharpWinForms/CSharpWinForms.csproj
- samples/CSharpWinForms/Form1.Designer.cs
- samples/CSharpWinForms/Form1.cs
- samples/CSharpWinForms/Form1.resx
- samples/CSharpWinForms/MemoryLogger.cs
- samples/CSharpWinForms/Program.cs
- samples/CSharpWinForms/README.md
- samples/CSharpWinForms/build.bat
This adds a WinForms sample similar to the WPF one.
> Adding Windows Forms sample

- src/bins/src/windows/mitigate.rs
- src/vpk/Velopack.Deployment/GitHubHttpClient.cs
> Dynamically load SetDefaultDllDirectories

- src/lib-csharp/ReleaseEntry.cs
- src/lib-csharp/VelopackAsset.cs
- src/lib-csharp/Windows/Shortcuts.cs
- src/vpk/Velopack.Packaging.Windows/Commands/WindowsPackCommandRunner.cs
Fixed minor typos in comments.
A couple updates to collection expressions.
> Fixing obsolete messages to reference the new class name

- src/vpk/Velopack.Deployment/GiteaRepository.cs
- test/Velopack.Packaging.Tests/GiteaDeploymentTests.cs
This fixes the issue #489 what prevents the release from to be merged.
Also added the tests for Gitea
> Gitea merge fix

- src/lib-csharp/Locators/IVelopackLocator.cs
- src/lib-csharp/Locators/LinuxVelopackLocator.cs
- src/lib-csharp/Locators/OsxVelopackLocator.cs
- src/lib-csharp/Locators/TestVelopackLocator.cs
- src/lib-csharp/Locators/VelopackLocator.cs
- src/lib-csharp/Locators/WindowsVelopackLocator.cs
- src/lib-csharp/UpdateManager.Helpers.cs
- src/lib-csharp/Util/IoUtil.cs
- src/lib-csharp/VelopackApp.cs
- src/lib-csharp/VelopackRuntimeInfo.cs
> Make ProcessInfo mockable, to help unusual setups and Unity

- src/vpk/Velopack.Build/PackTask.cs
- src/vpk/Velopack.Build/Velopack.Build.targets
- src/vpk/Velopack.Packaging.Unix/Commands/OsxPackCommandRunner.cs
- src/vpk/Velopack.Packaging.Unix/Commands/OsxPackOptions.cs
- src/vpk/Velopack.Packaging.Unix/OsxBuildTools.cs
- src/vpk/Velopack.Vpk/Commands/Packaging/OsxPackCommand.cs
> Allow disabling of deep signing on macos

- Cargo.lock
- src/lib-rust/Cargo.toml
- src/lib-rust/src/download.rs
> Fix: rust download not propagating errors

- Cargo.lock
- Cargo.toml
- src/lib-cpp/src/csource.rs
- src/lib-csharp/Locators/VelopackLocator.cs
- src/lib-csharp/Sources/VelopackFlowUpdateSource.cs
- src/lib-csharp/UpdateManager.cs
- src/lib-csharp/Util/EnumerableExtensions.cs
- src/lib-rust/Cargo.toml
- src/lib-rust/src/locator.rs
- src/lib-rust/src/manager.rs
- src/lib-rust/src/sources.rs
- src/vpk/Velopack.Build/PublishTask.cs
- src/vpk/Velopack.Flow/Commands/PublishCommandRunner.cs
- src/vpk/Velopack.Flow/Commands/PublishOptions.cs
- src/vpk/Velopack.Flow/FlowApi.g.cs
- src/vpk/Velopack.Flow/FlowApiExtensions.cs
- src/vpk/Velopack.Flow/VelopackFlowServiceClient.cs
- src/vpk/Velopack.Vpk/Commands/Flow/PublishCommand.cs
- src/vpk/Velopack.Vpk/Commands/SystemCommandLineExtensions.cs
- test/Velopack.Tests/TestHelpers/FakeDownloader.cs
- test/Velopack.Tests/TestHelpers/FakeFixtureRepository.cs
- test/Velopack.Tests/Velopack.Tests.csproj
This adds in tiered rollout support for Flow.
This adds an additional parameter to vpk flow publish to allow settings the tiered publish percentage for a new release.
> Implementing Tiered Rollout for Flow
