- docfx/docs/distributing/deployment.md
- docfx/docs/index.md
This pull requests includes the following changes:
- Fixed a broken link on the home page
- Added a page regarding continuous deployment and populated a guide for GitHub Actions
Please note that my personal workflow doesn't use `vpk download github` or `vpk upload github` due to having an atypical way of handling releases. The rest of the workflow has been tested across multiple releases though. However, it would be beneficial for maintainers to confirm that the usage stated in the final code block is correct.
I welcome any feedback and would be more than happy to make any changes if required.
> Documentation update (link fix, GitHub Action for Continuous Deployment)

- src/Velopack/Compression/DeltaPackage.cs
- test/Velopack.Packaging.Tests/WindowsPackTests.cs
This fix resolved my issue where new DLLs present in deltas were not being applied to the application when updating.
I'm still very new to Velopack's code, so it would be worth a little scrutiny before merging in.
> fix: ensure new files are applied from deltas

- src/Velopack/Compression/DeltaPackage.cs
This change handles a case where a file is added in a new version, but the directory path does not exist in the current local version.
Before this change the system would gracefully fallback to pulling the full version download. With this change it will allow the delta patch to be applied and reduces the re-download of the full install.
> Ensure directory path exists when adding a new file during ApplyDeltaPackageFast

- src/Velopack.Deployment/GitHubRepository.cs
- src/Velopack.Vpk/Commands/Deployment/GitHubUploadCommand.cs
- test/Velopack.CommandLine.Tests/Commands/GitHubCommandTests.cs
- test/Velopack.Packaging.Tests/GithubDeploymentTests.cs
Currently, when creating a new release using the `vpk upload github` command, if the tag doesn't exist, it creates a new tag for the default branch, usually `main` or `master`. In scenarios where creating a beta release from the `develop` branch and setting the tag name to the version generated by an auto-increment tool like GitVersion, a mismatch between the branch and the tag may affect further version calculations. To avoid this, users should define a tag for the `develop` branch themselves and call the upload command with this tag as an option. This PR introduces the `targetCommitish` option, which allows setting from which branch or commit the new tag should be created.
> Vpk Upload GitHub - add targetCommitish option

- src/Velopack.Deployment/S3Repository.cs
DisablePayloadSigning = true and DisableDefaultChecksumValidation = false to greater compatibility with S3 priverders
. Oracle/Cloudflare doesn't support Streaming SigV4 which is used in [chunked uploading](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html) as decribed in https://kian.org.uk/cloudflare-r2-and-aws-sdk-for-net/.
theoretically we can try upload and if fails use this new apporach but exception occurs AFTER upload. And due to my reaearch this cannot be easly checked upfront..
> DisablePayloadSigning in S3 deployment

- src/Directory.Build.targets
- src/Velopack/Internal/Utility.cs
- src/Velopack/Sources/VelopackFlowUpdateSource.cs
- src/Velopack/UpdateManager.cs
- test/Velopack.Tests/UpdateManagerTests.cs
*Long story*
I saw that SimpleWebSource seems to support specifying absolute url's in the "Filename" path of releases.json so I did try a scenaro with "releases.json" from one website and the .nupkg files from another location only to get download problems because the UpdateManager tried to create a file named "https://my.domain/client/mypackage." which contains invalid filename characters.
I suppose you can get the similar problems if you make the path relative (I assume "../../filename" fill put the downloaded file in the completely wrong folder .
I've made the quickest possible fix and only uses the filename part when choosing what the temporary downloaded file should be called (and verified that the update works as expected).
> FIx downloading of files from absolute or relative paths

- src/Velopack.Packaging.Unix/Commands/LinuxPackCommandRunner.cs
- src/Velopack.Packaging.Unix/Commands/LinuxPackOptions.cs
- src/Velopack.Vpk/Commands/LinuxPackCommand.cs
- src/Velopack.Vpk/Commands/_BaseCommand.cs
- src/Velopack.Vpk/Commands/_PackCommand.cs
On Mac, you can pass your compiler output or a pre-built .app folder to --packDir, so this PR just matches that logic on Linux. If the provided folder ends in `.AppDir` it will be recognized as an appdir. Otherwise, an appdir will be built as normal.
> Remove the --appDir argument

- src/Rust/src/commands/apply_windows_impl.rs
- src/Rust/src/shared/bundle.rs
- src/Rust/src/shared/util_common.rs
- src/Rust/src/windows/splash.rs
The "Access denied" errors when performing updates have been occurring for users - sometimes because of user error, but possibly sometimes due to transient errors like AV involvement etc. 
This PR completely re-writes the windows update logic. We will still try a fast rename, but if that fails we will fall back to robocopy instead which can work in a variety of new circumstances (such as a non-vital file being locked, or a cmd.exe running in the current directory)
Closes #159
> More resilient windows update logic

- src/Velopack.Vpk/Commands/LinuxPackCommand.cs
- src/Velopack.Vpk/Commands/OsxBundleCommand.cs
- src/Velopack.Vpk/Commands/WindowsPackCommand.cs
- src/Velopack.Vpk/Commands/_OutputCommand.cs
- src/Velopack.Vpk/Commands/_PackCommand.cs
- src/Velopack.Vpk/Commands/_PlatformCommand.cs
I saw another opportunity to instead include the channel into the VelopackDefaults but I think this better.
> Fixed default channel when using cross-compile directive

- src/Velopack/Sources/SimpleFileSource.cs
- src/Velopack/Sources/SimpleWebSource.cs
- src/Velopack/Sources/VelopackFlowUpdateSource.cs
This PR converts methods of `VelopackFlowUpdateSource`, `SimpleWebSource` and `SimpleFileSource` to `virtual`.
In some cases I need to override and add pre-job or post-job without changing the main logic. Since the [Utility](https://github.com/velopack/velopack/blob/83dfef507311843849abdc388ac4be4cc513c5ea/src/Velopack/Internal/Utility.cs#L17) class is not public, it's not possible to duplicate code to add codes around it. This PR allows extending existing sources
> Allow extending pre-defined sources from SDK

- src/lib-csharp/NuGet/NugetUtil.cs
- test/Velopack.Packaging.Tests/ReleasePackageTests.cs
- test/Velopack.Tests/NugetUtilTests.cs
> Fixed: Fixed semver version check - 0.0.1 is now allowed with a release label (e.g. 0.0.1-beta)

- src/vpk/Velopack.Packaging.Unix/Commands/OsxPackCommandRunner.cs
- test/Velopack.Packaging.Tests/OsxPackTests.cs
- test/Velopack.Packaging.Tests/TestApp.cs
Fixes https://github.com/velopack/velopack/issues/186
Hello!
I believe this is only an issue on macOS, because no other system has zipped-up app bundles, but when executing a command of the form:
```
[osx] pack --packTitle="My App" --packId="myapp" --runtime="osx-arm64" ...
```
The output is currently:
```
myapp-osx-arm64-Portable.zip
|- myapp.app
```
When it should be:
```
myapp-osx-arm64-Portable.zip
|- My App.app
```
> Fix `--packTitle` not considered for macOS bundles

- src/vpk/Velopack.Vpk/Commands/SystemCommandLineExtensions.cs
Hi, 
I noticed today that the error is still occurring for me
Looks like I modified the part of the code in #208 that is no longer used
sorry 😄
> fix semver version check - 0.0.1 is now allowed with a release label

- src/vpk/Velopack.Packaging/HelperFile.cs
Perhaps I'm doing something wrong, if so let me know. The [build instructions](https://docs.velopack.io/contributing/compiling#release--build) appear to be out of date as the `src/Rust` folder doesn't exist and, going by the [Rust docs](https://doc.rust-lang.org/cargo/guide/build-cache.html#build-cache), the workspace root appears to be the repository root where [`Cargo.lock`](https://github.com/velopack/velopack/blob/ca71471cbd9893f2510c06ecd14225751d6b8116/Cargo.lock) is located.
Sample output on macOS:
```
~/Repos/velopack $ git clean -xdf
~/Repos/velopack $ cargo build -q
~/Repos/velopack $ find . -type f -perm +u=x -name "*update*"
./target/debug/update
./target/debug/deps/update-e139ada1f22d8d06
./.git/hooks/post-update.sample
./.git/hooks/update.sample
```
update.exe is placed in …
> Fix updater search path in DEBUG builds

- src/vpk/Velopack.Packaging.Windows/SetupBundle.cs
Fix In SetupBundle.cs   FindBundleHeader will throw new Exception("PlaceHolderNotFoundInAppHostException"); in IsBundle() when building large installer > 2.5Gb on windows system
The search pattern was never found
> Fix issue with generating SetupBundle for large bundle

- src/vpk/Velopack.Vpk/Program.cs
- src/vpk/Velopack.Vpk/Updates/UpdateChecker.cs
- src/vpk/Velopack.Vpk/VelopackDefaults.cs
This adds in a new option to the root of the vpk command to allow for skipping update checks.
This is often desirable for things like automations that don't want additional checks to be performed.
> Allow for skipping update check

- src/vpk/Velopack.Packaging.Windows/CodeSign.cs
- src/vpk/Velopack.Packaging.Windows/Commands/WindowsPackCommandRunner.cs
We've recently updated to use [Azure Trusted Signing](https://learn.microsoft.com/en-us/azure/trusted-signing/how-to-signing-integrations) and as part of the process `signtool` is given a [dlib DLL](https://learn.microsoft.com/en-us/azure/trusted-signing/how-to-signing-integrations#download-and-install-the-trusted-signing-dlib-package) that implements the signing function.
The complete setup looks like this: https://github.com/ppy/osu-deploy/blob/c8c9b70b0e1ad14711ae8976a86f4644c72cf15d/Builders/WindowsBuilder.cs#L32-L52
Importantly, the Azure signing dlib is a .NET 6 module. For us, it was failing to load with the exception:
```
Unhandled managed exception
System.TypeLoadException: Could not load type 'Internal.Runtime.CompilerServices.Unsafe' from assembly 'System.Private.CoreLib, …
```
> Give signtool absolute paths to the files to sign

- .github/workflows/build.yml
Right now if you push to a branch with an open PR, both the PR and an push triggers fire, causing the workflow to run twice. This limits it to only run on pushes to develop and master, or on PRs to those branches.
This also adds in a workflow_dispatch trigger to be able to manually kick runs from any branch if desired.
> Fixing double runs when pushing to a branch with an open PR

- src/vpk/Velopack.Packaging.Unix/OsxBuildTools.cs
I have had trouble setting up my dev environment to correctly build the vpk CLI to test this change works. 
Added a prefix of `export VELOPACK_FIRSTRUN=1` to the initial run of the installed app triggered in the postinstall script.
In theory, this should be available to Velopack to detect first run.
Closes #167
> Fix WithFirstRun not running on MacOS

- src/vpk/Velopack.Deployment/AzureRepository.cs
Overriden the default BlobClient options to change the network timeout from 100 seconds to 30 minutes.
should fix #377
> Increased azure repository network timeout to 30 minutes

- .github/workflows/build.yml
- src/vpk/Velopack.Build/PackTask.cs
- src/vpk/Velopack.Build/Velopack.Build.targets
- src/vpk/Velopack.Packaging.Windows/Commands/WindowsPackCommandRunner.cs
- src/vpk/Velopack.Packaging.Windows/Commands/WindowsSigningOptions.cs
- src/vpk/Velopack.Vpk/Commands/Packaging/WindowsPackCommand.cs
- test/Velopack.CommandLine.Tests/Commands/WindowsCommandTests.cs
This allows the caller to specify a regex pattern to exclude files. When specified the default filter no longer applies.
> Adding --signExclude parameter

- src/vpk/Velopack.Packaging/Velopack.Packaging.csproj
- test/LegacyTestApp/LegacyTestApp.csproj
Updating transitive System.Text.Json package.
Ignoring vulnerable package in legacy app.
PR #462 has the fix needed for the pipeline.
> Fixing vulnerable NuGet packages

- src/bins/src/setup.rs
- src/bins/src/update.rs
- src/lib-csharp/Windows/Runtimes.cs
- src/vpk/Velopack.Packaging.Windows/Commands/WindowsPackCommandRunner.cs
- src/vpk/Velopack.Vpk/Commands/Packaging/WindowsPackCommand.cs
The bootstrapping link has been brokens since we moved docs to its own repo. This instead uses the docs web page address.
Redirected CLI output to point to the web site rather than the repo URL.
> Fixing URL links

- src/vpk/Velopack.Flow/VelopackFlowServiceClient.cs
The base URI was not combined making the error message incorrect. 
This fixes the merging and Flow E2E tests now pass.
> Velopack Flow API fix

- src/vpk/Velopack.Packaging.Windows/CodeSign.cs
Change how args are escaped for RunSigningCommand to fix issue with `'` on Linux
> Fix --signTemplate on Linux

- src/vpk/Velopack.Vpk/Commands/Packaging/WindowsPackCommand.cs
This leaves the MSI option available for future release if we decide to build a true MSI installer.
> Proposal for a rename to the CLI options

- src/vpk/Velopack.Packaging.Unix/Commands/OsxPackCommandRunner.cs
Make sure to sign sq.version since it is inside of the Contents/MacOS. Otherwise signing will fail. Resolves: https://github.com/velopack/velopack/issues/507
> Fixed signDisableDeep complaining about sq.version

- src/vpk/Velopack.Deployment/S3Repository.cs
- src/vpk/Velopack.Vpk/Commands/Deployment/S3BaseCommand.cs
`ForcePathStyle` may not be `true` all the time.
For example Alibaba Cloud OSS need's it be `false`.
so I make it configurable, and default to be `true`
> Add option forcePathStyle for s3 deployment

- src/vpk/Velopack.Flow/HmacAuthHttpClientHandler.cs
This fixes an issue with the API key auth with Flow assuming the external URL will match the internal one (which fails when put being a gateway with TLS termination)
> Updating HMAC signature

- src/bins/src/update.rs
- src/vpk/Velopack.Vpk/Velopack.Vpk.csproj
- test/Velopack.Packaging.Tests/WindowsPackTests.cs
When using the Squirrel CLI to perform updates, Update.exe becomes locked and can not be updated. There is a mechanism in Squirrel to "--updateSelf" after the application update. This adds that command to Velopack.
Closes #632
> Fix Squirrel CLI migrations by adding --updateSelf command

- .github/workflows/build.yml
- src/lib-csharp/Sources/GitBase.cs
- src/lib-csharp/Sources/GiteaSource.cs
- src/lib-csharp/Sources/GithubSource.cs
- src/lib-csharp/Sources/GitlabSource.cs
- src/lib-csharp/Sources/HttpClientFileDownloader.cs
- src/lib-csharp/Sources/IFileDownloader.cs
- test/Velopack.Tests/TestHelpers/FakeDownloader.cs
- test/Velopack.Tests/TestHelpers/FakeFixtureRepository.cs
@caesay this is my take on the changes related to header updates as discussed in #641
I explicitly wanted to split this so this update does NOT include the actual problematic changes related to the self hosted gitlab instance.
Also, I had some issues with unit tests on my machine. I'll need  to await a CI build (hopefully, there is one 😄 )
Attention: As discussed, this Api is breaking the API without fall back compatibility when using custom Downloaders.
> Refactor downloader methods to use a dictionary for headers

- src/lib-csharp/Sources/GitlabSource.cs
Do not assume that that base Url is always https://gitlab.com and also, correctly handle potential trailing slash issue.
> Fix for self hosted Gitlab Url for Release Source
